import { getDb } from "../../db/db";

const now = () => Date.now();

// ─── Attention items ──────────────────────────────────────────────────────────
// These are server-generated by a Firebase Cloud Function or Supabase edge
// function that analyses purchase_hubs. The app reads and dismisses them;
// it never creates them. There is no dirty/sync_status — dismissal is an
// optimistic local UI action that is confirmed by the server removing the item
// from attention_items/{uid} on the next sync cycle.

export async function upsertAttentionItem(userUid, item) {
  const db = await getDb();
  const t = now();
  const linked = item.linked_entity || {};
  await db.runAsync(
    `INSERT INTO attention_items (
       user_uid, attention_id, title, description, type,
       severity, status, sort_order, due_date,
       linked_entity_type, linked_entity_id, actions_json,
       created_at_ms, updated_at_ms, last_synced_at
     ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(user_uid, attention_id) DO UPDATE SET
       title=excluded.title,
       description=excluded.description,
       type=excluded.type,
       severity=excluded.severity,
       status=excluded.status,
       sort_order=excluded.sort_order,
       due_date=excluded.due_date,
       linked_entity_type=excluded.linked_entity_type,
       linked_entity_id=excluded.linked_entity_id,
       actions_json=excluded.actions_json,
       updated_at_ms=excluded.updated_at_ms,
       last_synced_at=excluded.last_synced_at`,
    [
      String(userUid),
      String(item.attention_id),
      String(item.title || ""),
      item.description || null,
      item.type || null,
      String(item.severity || "low"),
      String(item.status || "open"),
      Number(item.sort_order ?? 99),
      item.due_date || null,
      linked.type || null,
      linked.id || null,
      Array.isArray(item.actions) ? JSON.stringify(item.actions) : (item.actions_json || null),
      Number(item.created_at_ms || item.created_at || t),
      Number(item.updated_at_ms || item.updated_at || t),
      t,
    ]
  );
}

/**
 * List open attention items for a user, ordered by severity then sort_order.
 * Severity order: high=0, medium=1, low=2.
 */
export async function listAttentionItems(userUid, limit = 20) {
  const db = await getDb();
  return await db.getAllAsync(
    `SELECT *,
       CASE severity WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END AS sev_order
     FROM attention_items
     WHERE user_uid=? AND status='open'
     ORDER BY sev_order ASC, sort_order ASC
     LIMIT ?`,
    [String(userUid), Number(limit)]
  );
}

export async function countOpenAttentionItems(userUid) {
  const db = await getDb();
  const row = await db.getFirstAsync(
    `SELECT COUNT(*) AS c FROM attention_items WHERE user_uid=? AND status='open'`,
    [String(userUid)]
  );
  return Number(row?.c || 0);
}

/**
 * Optimistically dismiss an attention item locally.
 * The item will be removed on the next Firebase sync cycle when the server
 * confirms it is resolved.
 */
export async function dismissAttentionItem(userUid, attentionId) {
  const db = await getDb();
  await db.runAsync(
    `UPDATE attention_items SET status='dismissed', updated_at_ms=?
     WHERE user_uid=? AND attention_id=?`,
    [now(), String(userUid), String(attentionId)]
  );
}

/**
 * After a full Firebase snapshot, remove any attention items not in the
 * server's current set (they were resolved server-side).
 */
export async function reconcileAttentionItems(userUid, keepIds) {
  const db = await getDb();
  const rows = await db.getAllAsync(
    `SELECT attention_id FROM attention_items WHERE user_uid=?`,
    [String(userUid)]
  );
  const keep = new Set((keepIds || []).map(String));
  for (const { attention_id } of rows) {
    if (!keep.has(String(attention_id))) {
      await db.runAsync(
        `DELETE FROM attention_items WHERE user_uid=? AND attention_id=?`,
        [String(userUid), String(attention_id)]
      );
    }
  }
}
