import { StyleSheet } from "react-native";
import { scale, getFontSize } from "../utils/responsive";


export const VaultColors = {
  brandGoldDark: "#B37A1F",
  waves:"#683e03",
  brown:"#5B3B1F",
  brandGold: "#B37A1F",
  brandGoldLight: "#DFA94D",
  brandGoldSoft: "#F6D586",
  brandCream: "#FEF7E6",
  sheetcolor: "#F5E4BF",
  appBackground: "#FEF7E6",
  surface: "#FEF7E6",
  surfaceAlt: "#FFFFFF",
  surfaceMuted: "#FFF9EF",
  surfaceRaised: "#FFFDF8",
  overlay: "rgba(30, 17, 4, 0.18)",
  textPrimary: "#8A5509",
  textSecondary: "#B37A1F",
  textMuted: "#DFA94D",
  textSoft: "#A77526",
  textOnDark: "#FEF7E6",
  iconDefault: "#8A5509",
  iconMuted: "#DFA94D",
  border: "#F6D586",
  divider: "#F6D586",
  borderStrong: "#DFA94D",
  navBackground: "#FEF7E6",
  navActiveIndicator: "#8A5509",
  navIcon: "#8A5509",
  navIconInactive: "#DFA94D",
  cardBackground: "#FFFFFF",
  cardBackgroundAlt: "#FFF9EF",
  cardBorder: "#F6D586",
  cardShadow: "rgba(138, 85, 9, 0.10)",
  buttonPrimary: "#B37A1F",
  buttonPrimaryPressed: "#8A5509",
  buttonSecondary: "#8A5509",
  buttonSecondaryPressed: "#8A5509",
  buttonOutline: "#FEF7E6",
  buttonOutlinePressed: "#F6D586",
  buttonOutlineBorder: "#F6D586",
  buttonGhost: "transparent",
  buttonTextOnGold: "#FEF7E6",
  buttonTextOnBlack: "#FEF7E6",
  success: "#18A957",
  successSoft: "#E8F8EE",
  warning: "#E0A100",
  warningSoft: "#FFF6E3",
  error: "#D64545",
  errorSoft: "#FDECEC",
  info: "#2E6BD8",
  infoSoft: "#EEF4FF",
  inputBackground: "#FFFFFF",
  inputBorder: "#F6D586",
  inputFocusedBorder: "#B37A1F",
  inputText: "#8A5509",
  inputPlaceholder: "#DFA94D",
  statusBarBackground: "#FEF7E6",
  statusBarText: "#8A5509",
  waveA: "#F6D586",
  waveB: "#DFA94D",
  waveC: "#B37A1F",
};

export const VaultTypography = {
  fontFamily: "Poppins",
  fontWeights: {
    light: "300",
    regular: "400",
    medium: "500",
    semiBold: "600",
    bold: "700",
  },

  h1: {
    fontFamily: "Poppins",
    fontSize: 34,
    fontWeight: "700",
    lineHeight: 40,
    color: VaultColors.textPrimary,
  },
  h2: {
    fontFamily: "Poppins",
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
    color: VaultColors.textPrimary,
  },
  h3: {
    fontFamily: "Poppins",
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 26,
    color: VaultColors.textPrimary,
  },
  h4: {
    fontFamily: "Poppins",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 24,
    color: VaultColors.textPrimary,
  },
  body1: {
    fontFamily: "Poppins",
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 22,
    color: VaultColors.textPrimary,
  },
  body2: {
    fontFamily: "Poppins",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 20,
    color: VaultColors.textSecondary,
  },
  body3: {
    fontFamily: "Poppins",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
    color: VaultColors.textMuted,
  },
  headerTitle: {
    fontFamily: "Poppins",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 22,
    color: VaultColors.textPrimary,
  },
  sectionTitle: {
    fontFamily: "Poppins",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 20,
    color: VaultColors.textPrimary,
  },
  captionGold: {
    fontFamily: "Poppins",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    color: VaultColors.textSecondary,
  },
};

export const VaultSpacing = {
  xs: scale(4),
  sm: scale(8),
  md: scale(14),
  lg: scale(20),
  xl: scale(28),
  xxl: scale(40),
  screenPadding: scale(22),
  cardPadding: scale(16),
  sectionSpacing: scale(20),
  itemSpacing: scale(12),
};

export const VaultRadius = {
  xs: scale(6),
  sm: scale(10),
  md: scale(14),
  lg: scale(18),
  xl: scale(26),
  full: scale(999),
  card: scale(18),
  button: scale(18),
  input: scale(14),
  chip: scale(999),
};

export const VaultShadows = {
  sm: {
    shadowColor: VaultColors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  md: {
    shadowColor: VaultColors.textPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
  },
  lg: {
    shadowColor: VaultColors.textPrimary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.13,
    shadowRadius: 22,
    elevation: 7,
  },
};

export const VaultAnimations = {
  fast: 140,
  normal: 260,
  slow: 420,
};

export const VaultCommonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: VaultColors.appBackground,
  },
  screen: {
    flex: 1,
    backgroundColor: VaultColors.appBackground,
    paddingHorizontal: VaultSpacing.screenPadding,
    paddingTop: VaultSpacing.lg,
  },
  card: {
    backgroundColor: VaultColors.cardBackground,
    borderRadius: VaultRadius.card,
    padding: VaultSpacing.cardPadding,
    borderWidth: 1,
    borderColor: VaultColors.cardBorder,
    ...VaultShadows.sm,
  },
  raisedCard: {
    backgroundColor: VaultColors.surfaceRaised,
    borderRadius: VaultRadius.xl,
    padding: VaultSpacing.cardPadding,
    borderWidth: 1,
    borderColor: VaultColors.cardBorder,
    ...VaultShadows.md,
  },
  mutedCard: {
    backgroundColor: VaultColors.cardBackgroundAlt,
    borderRadius: VaultRadius.card,
    padding: VaultSpacing.cardPadding,
    borderWidth: 1,
    borderColor: VaultColors.border,
  },
  buttonBase: {
    minHeight: scale(52),
    borderRadius: VaultRadius.button,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: VaultSpacing.lg,
    flexDirection: "row",
  },
  input: {
    minHeight: scale(50),
    backgroundColor: VaultColors.inputBackground,
    borderRadius: VaultRadius.input,
    borderWidth: 1,
    borderColor: VaultColors.inputBorder,
    paddingHorizontal: VaultSpacing.md,
    color: VaultColors.inputText,
  },
  pill: {
    minHeight: scale(32),
    borderRadius: VaultRadius.full,
    paddingHorizontal: VaultSpacing.md,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: VaultColors.surfaceMuted,
    borderWidth: 1,
    borderColor: VaultColors.border,
  },
  row: { flexDirection: "row" },
  center: { alignItems: "center", justifyContent: "center" },
  spaceBetween: { justifyContent: "space-between" },
  flex1: { flex: 1 },
});

export const VaultTypographyStyles = StyleSheet.create({
  h1: { ...VaultTypography.h1, fontSize: getFontSize(VaultTypography.h1.fontSize) },
  h2: { ...VaultTypography.h2, fontSize: getFontSize(VaultTypography.h2.fontSize) },
  h3: { ...VaultTypography.h3, fontSize: getFontSize(VaultTypography.h3.fontSize) },
  h4: { ...VaultTypography.h4, fontSize: getFontSize(VaultTypography.h4.fontSize) },
  body1: { ...VaultTypography.body1, fontSize: getFontSize(VaultTypography.body1.fontSize) },
  body2: { ...VaultTypography.body2, fontSize: getFontSize(VaultTypography.body2.fontSize) },
  body3: { ...VaultTypography.body3, fontSize: getFontSize(VaultTypography.body3.fontSize) },
  headerTitle: { ...VaultTypography.headerTitle, fontSize: getFontSize(VaultTypography.headerTitle.fontSize) },
  sectionTitle: { ...VaultTypography.sectionTitle, fontSize: getFontSize(VaultTypography.sectionTitle.fontSize) },
  captionGold: { ...VaultTypography.captionGold, fontSize: getFontSize(VaultTypography.captionGold.fontSize) },
});

export default {
  VaultColors,
  VaultTypography,
  VaultSpacing,
  VaultRadius,
  VaultShadows,
  VaultAnimations,
  VaultCommonStyles,
  VaultTypographyStyles,
};
